spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:db_olga}
    username: ${POSTGRES_USER:nexoc}
    password: ${POSTGRES_PASSWORD:0880}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never # always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8001

base:
  url: "http://localhost:8001"

db:
  container-name: ${POSTGRES_CONTAINER_NAME:db_olga}
  name: ${POSTGRES_DB:db_olga}
  user: ${POSTGRES_USER:nexoc}
  password: ${POSTGRES_PASSWORD:0880}

file:
  upload-dir: ${UPLOAD_DIR:./uploads}

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    at.magic.olga: DEBUG
    at.magic.olga.service.ExportService: DEBUG
